services:
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=contato@tobiasmarion.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  chatstats:
    image: tobiasmarion/chatstats:latest
    secrets:
      - chatstats-db-uri
    environment:
      - DATABASE_URI=/run/secrets/chatstats-db-uri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatstats.rule=Host(`chatstats.tobiasmarion.com`)"
      - "traefik.http.routers.chatstats.entrypoints=websecure"
      - "traefik.http.routers.chatstats.tls.certresolver=le"

secrets:
  chatstats-db-uri:
    external: true