services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=contato@tobiasmarion.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  chatstats:
    image: tobiasmarion/chatstats:latest
    container_name: chatstats
    restart: unless-stopped
    secrets:
      - DATABASE_URI
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatstats.rule=Host(`chatstats.tobiasmarion.com`)"
      - "traefik.http.routers.chatstats.entrypoints=websecure"
      - "traefik.http.routers.chatstats.tls.certresolver=le"
    networks:
      - web

secrets:
  DATABASE_URI:
    file: ./secrets/DATABASE_URI

networks:
  web:
    external: true