name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set timestamp
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tobiasmarion/chatstats:$IMAGE_TAG
    - name: Push image to Docker Hub
      run: |
          docker login -u tobiasmarion -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tobiasmarion/chatstats:$IMAGE_TAG
